### ISSUE TITLE
[Request] Consider uploading forwarder zip to (public) S3 bucket

### ISSUE THREAD

**Issue by BeyondEvil** [DataDog/datadog-serverless-functions#223]
Please consider uploading the production release of the aws-dd-forwarder zip-file to a public S3 bucket (read-only of course).

Users can then directly source the zip in AWS instead of having to either clone and package the repo or pull down the zip from `Releases`.

Preferably without the "noise" (tests directory, shell scripts, etc) 😊

**Comment by tianchu** [comment]
Hi @BeyondEvil thanks for the suggestion! I agree what you described is the ideal experience for users.

The current zip copier approach isn't ideal, it but otherwise, we have to create a bucket for each AWS region (and create new ones when they are added) and AWS China and GovCloud partitions (we don't yet have AWS accounts in those partitions to create S3 buckets).

We do have a plan to eventually host the zip file in S3 and save the zip copier approach as a fallback solution for special AWS partitions only.

**Comment by agocs** [comment]
SLS-1323

**Comment by tianchu** [comment]
https://github.com/DataDog/datadog-serverless-functions/pull/465 did get rid of the secondary zip copier lambda function, and hosted the majority of the function code in a public Lambda layer that everyone can source. Although it's a different approach, but I believe it does solve the same problem. Closing.
