### ISSUE TITLE
Update version requires deploying new stack

### ISSUE THREAD

**Issue by hc-danieltiziani** [DataDog/datadog-serverless-functions#226]
**Describe what you expected:**
Some way to be possible to update the lambda code for the forwarder without destroying and creating a new one, because I need to attach to a specific ARN the log subscriptions and I'd need to redeploy a lot of lambdas to do this.

Maybe work with the code on a S3 and/or Terraform instead of just destroying and creating again. I think this will affect a lot of people using datadog, so I'd like to check if I'm not missing anything or if some thing is in the current plans to improve this update process.

**Comment by tianchu** [comment]
Hi @hc-danieltiziani,

Since version 3.0.0, the forwarder can be [updated](https://github.com/DataDog/datadog-serverless-functions/tree/master/aws/logs_monitoring#updating) through CloudFormation "Update", which only modifies certain resources (e.g., the function code) and does not recreate the lambda. 

[Updating](https://github.com/DataDog/datadog-serverless-functions/tree/master/aws/logs_monitoring#upgrade-an-older-version-to-300) from an older version to +3.0.0 does requires a little bit effort, , but the good news is that once you get there, future updates will be "one-click" without interruption. In fact, we migrated from SAM/SAR to CloudFormation to solve this exact problem (customers used to have recreate the lambda to update and manually copy over environment variables).

If you would like to keep the forwarder Lambda's ARN same as the old one, you can set the `FunctionName` [parameter](https://github.com/DataDog/datadog-serverless-functions/blob/master/aws/logs_monitoring/template.yaml#L18) (available in CFN stack configuration UI) to reuse the existing forwarder's name. I recommend you follow these steps: 

1. deploy the forwarder with a different name
1. migrate a few log subscriptions to it and test throughly
1. [export](https://stackoverflow.com/questions/41205890/download-an-already-uploaded-lambda-function) the old forwarder as a backup (just in case)
1. delete the old forwarder
1. update the existing CloudFormation stack and set `FunctionName` to the old forwarder's name

Does this answer your question? If I misunderstood your question, do you mind share extra context and specific requirements with us?

**Comment by hc-danieltiziani** [comment]
Hi @tianchu , it answers completely, thanks for the info.
If there is a way to update only the code with 3.0.0+ then it won't affect us at all, unless it has to destroy the lambda, so it's fine!

Thanks for the quick response! Closing issue.
