### ISSUE TITLE
ThrottledException in enhanced_lambda_metrics is not handled gracefully when running build_tags_by_arn_cache

### ISSUE THREAD

**Issue by azakordonets** [DataDog/datadog-serverless-functions#252]
**Describe what happened:**
It's not always, but we do get this error periodically : 
```
An error occurred (ThrottledException) when calling the GetResources operation (reached max retries: 4): Rate exceeded
```
<img width="1416" alt="Screenshot 2020-04-15 21 42 09" src="https://user-images.githubusercontent.com/1200012/79381322-1a1f4180-7f62-11ea-8947-a1dddc535ec3.png">
<img width="1419" alt="Screenshot 2020-04-15 21 42 36" src="https://user-images.githubusercontent.com/1200012/79381333-1d1a3200-7f62-11ea-9e5d-49e611e73249.png">

**Describe what you expected:**
It would be great if graceful retry would be implemented. I wanted to make a PR for this fix, but i have faced with couple problems : 
```python
def build_tags_by_arn_cache():
    """Makes API calls to GetResources to get the live tags of the account's Lambda functions

    Returns an empty dict instead of fetching custom tags if the tag fetch env variable is not set to true

    Returns:
        tags_by_arn_cache (dict<str, str[]>): each Lambda's tags in a dict keyed by ARN
    """
    tags_by_arn_cache = {}
    get_resources_paginator = resource_tagging_client.get_paginator("get_resources")

    try:
        for page in get_resources_paginator.paginate(
                ResourceTypeFilters=[GET_RESOURCES_LAMBDA_FILTER], ResourcesPerPage=100
        ):
            lambda_stats.distribution(
                "{}.get_resources_api_calls".format(ENHANCED_METRICS_NAMESPACE_PREFIX),
                1,
            )
            page_tags_by_arn = parse_get_resources_response_for_tags_by_arn(page)
            tags_by_arn_cache.update(page_tags_by_arn)

    except ClientError:
        log.exception(
            "Encountered a ClientError when trying to fetch tags. You may need to give "
            "this Lambda's role the 'tag:GetResources' permission"
        )

    log.debug(
        "Built this tags cache from GetResources API calls: %s", tags_by_arn_cache
    )

    return tags_by_arn_cache
```
1. Exception happens inside the loop of `paginator.paginate` iterable. We could
```python
    except ClientError:
        if e.response["Error"]["Code"] == "ThrottledException":
          # wait for random amount of time using jitter
          # if retries > 0: 
            # build_tags_by_arn_cache(retries=initital_retries - 1)
          # else:
            #log.exception("I have failed retrying N times")
```

but that would mean that we would have to retry from the beginning and not from the iterating point that we have failed. 
2. This method is using `lambda_stats.distribution` which is a part of DD layer and it means that we can't unit test this code, so no easy way to verify correctness of the fix

**Steps to reproduce the issue:**
Just subscribe many cloudwatch groups to dd lambda and then enable enhanced metrics logging. At some point it will choke.

**Comment by tianchu** [comment]
Hi @azakordonets, thanks for reporting this issue! Out of curiosity, do you notice any pattern when this error happens, like every x mins?

Speaking of retry with a jitter, we actually thought about it when this feature was implemented, but decided to not implement it for a few reasons.

- Instead of self-throttling the api calls in the function code, perhaps it's safer to simply reduce the [ReservedConcurrency](https://github.com/DataDog/datadog-serverless-functions/blob/master/aws/logs_monitoring/template.yaml#L39https://github.com/DataDog/datadog-serverless-functions/blob/master/aws/logs_monitoring/template.yaml#L39) of the forwarder and let AWS throttles the function? Either way, it means the logs ingestion will experience delays. Would you mind trying this out and let us know if it helps?
- Instead of adding retries, we would rather solve the root issue -- create a shared cache (perhaps a dynamodb table or s3 file or whatever is the cheapest) for all forwarder instances to use, which should dramatically reduce the # of api calls needed in the first place. We would love to hear your and the community's thoughts on this idea though.

**Comment by azakordonets** [comment]
Regarding occurence of the error - i've noticed that when i redeploy our lambda we get this error almost everytime. Could be because it tries to rebuild cache from scratch and makes too many requests. 

Unfortunately reducing ReservedConcurrency is not really an option for us because we want to have logs in Datadog as soon as possible, so i'm not gonna try that, sorry. Regarding better cache mechanism - sounds good to me . I don't have much preference as i don't have enough experience with using this services as caching mechanism. 


P.S. it's really pity that you guys have Datadog layers code laying in a different repo - it's makes impossible to write unit tests that would cover your datadog handler and enhanced metrics file. The way we use datadog adapter is that we have our own library - we do some manipulations and checks with cloudwatch logs before sending it to your handler. We love unit tests and it's really pity for me that i can't cover this "integration" parts with your code. 

P.P.S Why don't you have unit tests for both handler and enhanced metrics in this repo ?

**Comment by azakordonets** [comment]
I can add a bit more on occurence of this issue - for the last 2 hours i had this errors appearing about 5 times. And i have connected only 30% of all services that we have on our environment. I expect that if i will switch all our services to new datadog lambda, then i will get this errors way more :(

**Comment by tianchu** [comment]
@azakordonets regarding the `ReservedConcurrency`, it only affects the log ingestion if your forwarder's `aws.lambda.concurrent_executions.maximum` is constantly higher than the configured `ReservedConcurrency`. What does `aws.lambda.concurrent_executions.maximum` look like for your forwarder today? I suspect you only run into API throttling when `concurrent_executions` spikes, and when that happens retrying adds delay to log ingestion as well, same as throttling the forwarder execution.

If `concurrent_executions` is indeed very high constantly, an alternative solution is streaming all the logs to a Kinesis stream first and subscribe the forwarder to the Kinesis stream instead. You can control the batching and parallelization factor to find the optimal balance between latency and concurrent executions. Due to the batching, the concurrent executions of the forwarder should be dramatically lower.  Here are the instructions https://docs.datadoghq.com/integrations/amazon_web_services/?tab=allpermissions#advanced-ingesting-logs-with-kinesis

That being said, we are building better solutions on applying Lambda tags to logs, traces and metrics in the meantime, based on a completely different (very scalable) approach. That's why the `DdFetchLambdaTags` feature was marked as experimental and may gets replaced in the near future.

P.S., I'm not against the idea of adding retries with jitter, just trying to explain why we didn't add it in the first place. In fact, you can modify your forwarder code directly and try it out (assuming it's a quite simple code change) and it works perfectly fine for you, I'd love to get your PR merged asap :)

The layers have a good reason to be in its own repo, because they are not only for this forwarder Lambda functions, and they meant to be attached to customer Lambda functions to collect metrics, traces and etc.

We recently added integration tests to the forwarder, but we haven't added the unit tests yet, because we want to do some major code refactoring first.

If you have further questions on my suggested solutions, you can find me in our community slack channel: https://datadoghq.slack.com/channels/serverless/.

**Comment by tianchu** [comment]
We have a made a major improvement to solve the API throttling issue for `DdFetchLambdaTags` in the most recent [release](https://github.com/DataDog/datadog-serverless-functions/releases/tag/aws-dd-forwarder-3.19.0). The issue should have been resolved. Feel free to reach out to support@datadoghq.com if you still experience the issue after upgrading to the latest version.
