### ISSUE TITLE
cannot open trace-intake.so

### ISSUE THREAD

**Issue by mkravtsov-fetchrewards** [DataDog/datadog-serverless-functions#264]
I'm trying to deploy the dd-forwarder via cloudformation
https://github.com/DataDog/datadog-serverless-functions/releases/tag/aws-dd-forwarder-3.11.0

when forwarder is hit, the cloudwatch log reports this error

[ERROR] OSError: /var/task/trace_forwarder/bin/trace-intake.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/var/lang/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/var/lang/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/lambda_function.py", line 291, in <module>
    trace_connection = TraceConnection(DD_TRACE_INTAKE_URL, DD_API_KEY)
  File "/var/task/trace_forwarder/connection.py", line 23, in __init__
    self.lib = cdll.LoadLibrary("
{}
/bin/trace-intake.so".format(dir))
  File "/var/lang/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/var/lang/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)

**Comment by tianchu** [comment]
Hi @mkravtsov-fetchrewards I just deployed a testing forwarder using version 3.11.0 and it was forwarding traces fine. Did you change any default settings in CloudFormation? Do you have steps to reproduce?

**Comment by mkravtsov-fetchrewards** [comment]
Hi @tianchu - thank you for looking at this.

I tried it with bitbucket pipelines and the aws sam deploy image.

The only parameter that needs to be set it seems: is "DdApiKey."  I set that using STACK_PARAMETERS.

I also tried using sam build and sam deploy locally.

All have the same error.

If you have followable steps that work for you, can you please post?

Are you using CI/CD?

**Comment by tianchu** [comment]
@mkravtsov-fetchrewards Can you first try following these [steps](https://github.com/DataDog/datadog-serverless-functions/tree/master/aws/logs_monitoring#installation) and see whether it works for you? If yes, can you try compare what might be different between these steps and your CI/CD workflow?

**Comment by iojason** [comment]
@mkravtsov-fetchrewards @tianchu I just deployed aws-dd-forwarder 3.14.0 version and ran into the same error using aws sam. The problem is aws sam build does not copy .so files into the build folder. I just created a separate function after the build to copy the trace-intake.so file into the Forwarder and ForwarderZipCopier build folders. It's working better than the launch stack button because the log indicator in the dashboard is not green as intended. 

cp ./trace_forwarder/bin/trace-intake.so .aws-sam/build/Forwarder/trace_forwarder/bin
cp ./trace_forwarder/bin/trace-intake.so .aws-sam/build/ForwarderZipCopier/trace_forwarder/bin

**Comment by tianchu** [comment]
@jasondphan The forwarder is supposed to be deployed through CloudFormation (AWS console or CLI) rather than SAM CLI. Is there any reason why you must use SAM to deploy the forwarder?

**Comment by KIVagant** [comment]
@tianchu yes, there are some reasons not to use the provided CloudFormation template. First of all, it's overcomplicated (but very good as an example of what's required, of course). And it's somehow hard to integrate into existing environments, especially not CF-based. But not only because of this. The function overall is not very extendable and some people need to inject custom logic to make it work. In our case, for example, we have ready-to-use CI to deploy Lambda functions which works with AWS SAM only.

**Comment by KIVagant** [comment]
@tianchu , have you considered a possibility to extract trace_forwarder into a Lambda layer similar to https://github.com/DataDog/datadog-lambda-layer-python? If not, I'd like to request this feature.

UP: created [a separate issue](https://github.com/DataDog/datadog-serverless-functions/issues/306).

**Comment by jasondphan** [comment]
@tianchu - SAM is acting as a layer to organize and help simplify deployment; it's still calling aws cloudformation create-stack command under the hood. Datadog documentation even supports SAM  - https://docs.datadoghq.com/infrastructure/serverless/datadog_lambda_layer/#aws-sam. 

I noticed a new Datadog forwarder template was just released with the forwarder being nested in version 3.16. It now requires engineers to have to manually go in and add the wanted environment variables to the forwarder (DD_FORWARD_LOG, DD_FETCH_LAMBDA_TAGS, etc). Looks like we would need to pull/modify the template to avoid manual changes.
