### ISSUE TITLE
Feature request: ability to filter/reduce metric tags

### ISSUE THREAD

**Issue by tamasflamich** [DataDog/datadog-serverless-functions#266]
**Describe what happened:**

We are using the Log Forwarder Lambda for ingesting our logs and metrics to Datadog. Every time a metric is parsed, additional tags are injected (i.e. `DD_TAGS`, Forwarder Lambda Tags, `DD_FETCH_LAMBDA_TAGS`). This highly increases the cardinality of each metric and by that we end up having 10x more custom metrics compared to what we intend to have. The Datadog dashboard becomes noisy and we end up paying more.

**Describe what you expected:**

We would like to have the ability to specify a tag filter for metrics, so the increase of cardinality can be contained. 

```
DD_CUSTOM_METRIC_TAG_WHITELIST="tag1,tag2,tag_*"
```

This filtering could be applied at this point:
https://github.com/DataDog/datadog-serverless-functions/blob/8fd60e66984abfd901891b15ac037fceec4a0134/aws/logs_monitoring/lambda_function.py#L745

In case the owners agree that this is a useful feature, we are happy to submit this as an open source contribution.

**Comment by tianchu** [comment]
@tamasflamich these metrics are submitted as distribution metrics, you can filter out tags within the datadog platform https://docs.datadoghq.com/metrics/distributions/.

BTW, can you turn off `DD_FETCH_LAMBDA_TAGS` if you don't like those tags? Because you like to have them on logs?

Another thing to notice, custom metrics count by unique combination of tags rather than number of tags. Having more tags does not necessarily increase cardinality. https://docs.datadoghq.com/account_management/billing/custom_metrics/

**Comment by tamasflamich** [comment]
Hi @tianchu - Unfortunately, disabling `DD_FETCH_LAMBDA_TAGS` is not an option as we need those tags for logs (as you mentioned). We could have a separate Log Forwarder instance for metrics and logs, however, that would introduce a great deal of additional complexity.

As you suggested, I just used the distribution metric dashboard for reducing the number of tags. The problem with this approach is that we will need to do this every time we introduce a new metric. 

I'll check whether the number of custom metrics will drop with these changes. The "usage" dashboard should update within a day.

**Comment by tianchu** [comment]
@tamasflamich 

If you submit the same custom metric from the same lambda function, normally `DD_FETCH_LAMBDA_TAGS` shouldn't increase the cardinality, even though it increases the # of tags. Because unique combination of those lambda tags should be 1. 

BTW, you can also use the metric summaries page to find # of distinct metrics and # of tags for a specific metric name.

**Comment by tianchu** [comment]
Closing the issue due to inactivity.
