### ISSUE TITLE
Is datadog forwarder subscribes to otherthan cloudwatch logs, like s3,kinesis,sns? If yes, then how the subscription to other services happening?

### ISSUE THREAD

**Issue by bala1074** [DataDog/datadog-serverless-functions#323]
Is datadog forwarder subscribes to otherthan cloudwatch logs, like s3,kinesis,sns? If yes, then how the subscription to other services happening?

**Comment by bala1074** [comment]
@DarcyRaynerDD is datadog forwarder subscribes to only cloudwatch logs? I see in github forwarder code, presence of s3/kinesis/sns

**Comment by tianchu** [comment]
@bala1074 you have to set up the trigger (s3, kinesis, etc) on the Forwarder Lambda in AWS. Do you have a specific use case?

**Comment by tianchu** [comment]
@bala1074 I'm closing this issue since it's more like a question than issue. For how to set up triggers on the forwarder, see [here](https://docs.datadoghq.com/logs/guide/send-aws-services-logs-with-the-datadog-lambda-function/?tab=awsconsole#set-up-triggers). If you have more questions, feel free to sign up https://chat.datadoghq.com and find us in the #serverless channel.
