### ISSUE TITLE
Set a default value for DdApiKey

### ISSUE THREAD

**Issue by jgrumboe** [DataDog/datadog-serverless-functions#439]
Hi,

We are applying this stack via Terraform:
```
resource "aws_cloudformation_stack" "datadog_forwarder" {
  name         = local.datadog_lambda_name
  capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM", "CAPABILITY_AUTO_EXPAND"]
  parameters = {
    DdApiKey           = "this_value_is_not_used"
    DdApiKeySecretArn  = aws_secretsmanager_secret_version.dd_api_key.arn
    FunctionName       = local.datadog_lambda_name
    DdSite             = "datadoghq.eu"
    DdTags             = "env:${var.environment},team:${local.team},${var.datadog_additional_tag_structure}"
    LogRetentionInDays = 1
  }
  template_url = "https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/${var.datadog_log_forwarder_version}.yaml"
  tags         = { "Terraform" : "true" }

  # Ignore changes to DdApiKey, because it isn't used anyway, to mitigate unnecessary apply runs
  lifecycle {
    ignore_changes = [ parameters["DdApiKey"] ]
  }
}
```

Right now, we need to add the `lifecycle` stanza at the end, because DdApiKey can not be omitted, although we use DdApiKeySecretArn as input parameter for the stack.

There are also a lot of others running into this problem, because there's a terraform-provider-aws issue additionally: https://github.com/hashicorp/terraform-provider-aws/issues/55

Please, set a default value for DdApiKey.
https://github.com/DataDog/datadog-serverless-functions/blob/35fa153ab4b6ec9a05e07e57b6c331a29ef83fc9/aws/logs_monitoring/template.yaml#L9
This would allow Terraform user to omit this parameter, use DdApiKeySecretArn and omit the lifecycle workaround.

Thanks in advance,
Johannes

**Comment by tianchu** [comment]
@jgrumboe I did not give `DdApiKey` a default value only to make it to be required, so the majority of users (using `DdApiKey`) are given an error if no api key configured. Ideally I would love to give users an error if neither `DdApiKey` nor `DdApiKeySecretArn` is supplied, but CloudFormation is not flexible enough to achieve that. 

Since terraform is indeed very popular, I think it does make sense to add a default value for `DdApiKey` as you suggested. The downside is that if a user doesn't configure either `DdApiKey` nor `DdApiKeySecretArn`, no error would be given during the installation.

**Comment by jgrumboe** [comment]
Hi @tianchu,
@flonn found this blogpost https://aws.amazon.com/blogs/mt/how-to-perform-cross-parameter-validation-using-aws-cloudformation-rules-and-assertions/ writing about cross-parameter validation. Maybe this can help you out?
Otherwise, I do appreciate setting a default value 😏

**Comment by tianchu** [comment]
That is interesting, did not know that, will look into that feature. In the worst case, we'll set a default value.

**Comment by jgrumboe** [comment]
Thank you so much!
