### ISSUE TITLE
[RDS] create function fails

### ISSUE THREAD

**Issue by nodesocket** [DataDog/datadog-serverless-functions#44]
Tried multiple times and see:

<img width="1478" alt="screen shot 2018-07-10 at 5 45 17 pm" src="https://user-images.githubusercontent.com/523312/42541719-381177a8-8469-11e8-844a-0a489cc741be.png">

**Comment by Ricky-Thomas** [comment]
Hey @nodesocket sorry for the long delay here. Are you still experiencing this issue?

**Comment by nodesocket** [comment]
@Ricky-Thomas I was able to get the lambda function created, but I am now stuck on the step:

9.) Navigate to the Designer section and add a new trigger on the RDSOSMetrics CloudWatch Logs group.
10.) Give the filter a name and optional filter pattern and press Save.

I don't see `RDSOSMetrics CloudWatch Logs` trigger? Just to confirm, does the lambda function have to be in the same region as the RDS instance?

**Comment by Ricky-Thomas** [comment]
@nodesocket Thanks for getting back to me! Regarding the following:

> Just to confirm, does the lambda function have to be in the same region as the RDS instance?

This is indeed the case. 

`RDSOSMetrics CloudWatch Logs` should be a Log Group rather than a trigger. Check out this screenshot: https://cl.ly/af950c51bee4

See also: https://cl.ly/2c4b93929f6d

This should all be located under the "Designer" dropdown on the page of the specific function you're using. See here: https://cl.ly/ce2e6d5e04bb

Does this help? Are you seeing RDSOSMetrics as one of the Log Groups available for the newly created function?

Thanks again!

For reference, here is the doc for this on the Datadog side as well (pretty much the same stuff): https://docs.datadoghq.com/integrations/amazon_rds/#create-your-lambda-function

**Comment by nodesocket** [comment]
@Ricky-Thomas  Lambda is quite frustrating as you can't seem to use any function names you've used in the past. Anyway, whenever I try to deploy into N. California _(us-west-1)_ the same region as the RDS instance, the deploy of the function fails.

<img width="1295" alt="screen shot 2019-01-08 at 2 44 38 pm" src="https://user-images.githubusercontent.com/523312/50811913-f11e0300-1353-11e9-86d9-286f0816f1f3.png">

**Comment by garnermccloud** [comment]
I was able to successfully create the function with the documentation at https://docs.datadoghq.com/integrations/amazon_rds/#enhanced-rds-integration

@nodesocket - thanks for your patience. Have you verified that your `KMSKeyId` in the Application Settings section matches the key alias that you setup [here](https://docs.datadoghq.com/integrations/amazon_rds/#create-your-kms-key)?

**Comment by RaphaelAllier** [comment]
Hello, 

Doing some clean up in the repository's issues, I'm going to close this one as it's probably outdated.
If you have any more issues, feel free to open a Support ticket
