### ISSUE TITLE
[Request] DD log forwarder: Allow CF stack to be deleted/destroyed

### ISSUE THREAD

**Issue by vkakde** [DataDog/datadog-serverless-functions#469]
**Describe what happened:**
Datadog forwarder is set up in our AWS account to forward logs from lambdas, using [these](https://docs.datadoghq.com/serverless/libraries_integrations/forwarder/) steps. The forwarder uses DD's [CF stack](https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/latest.yaml), which is an IaC module in our infra. When we destroy our infra, CF stack fails to delete because S3 resource "ForwarderBucket" has an object (cache.json) in it. This causes our destroy pipelines to fail.

**Describe what you expected:**
DD's CF stack deletes seamlessly. Forwarder bucket should have force-delete enabled.

**Steps to reproduce the issue:**
1. Deploy [this](https://docs.datadoghq.com/serverless/libraries_integrations/forwarder/#sample-configuration) stack with terraform apply
2. terraform destroy yields:
`Error: error waiting for CloudFormation Stack deletion: failed to delete CloudFormation stack (DELETE_FAILED): ["The following resource(s) failed to delete: [ForwarderBucket]. " "The bucket you tried to delete is not empty (Service: Amazon S3; Status Code: 409; Error Code: BucketNotEmpty`

**Comment by agocs** [comment]
SLS-1302

**Comment by agocs** [comment]
Hi @vkakde , this is going to be a longer-running feature request. Unfortunately, the Lambda Forwarder is written as a Cloudformation Stack, and there is no native force-delete on Cloudformation stacks. There is [DeletionPolicy: Delete](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html), but that puts us back into the same position where it requires the S3 bucket to be empty first.

The supported method for deploying the Lambda Forwarder as a Terraform stack is simply wrapping the Cloudformation template in Terraform, and that does not give us access to [aws_s3_bucket](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#force_destroy)'s Force Destroy option. We would have to reimplement the Lambda Forwarder deployment in native terraform. I'm not against that, but it's an engineering effort.

There's also the option in which we implement a [bucket cleanup lambda function as a custom resource](https://stackoverflow.com/a/45007029). It's not the worst solution, but it needs thorough testing. 

I'm going to document these possibilities in our internal feature request so that our PMs can prioritize it accurately, but I'll close this issue for now. Please feel free to reopen or reach out to support@datadoghq.com in the mean time.

**Comment by jpogo** [comment]
@agocs Would it be possible to export the name/arn of the S3 bucket as a CF output? That way it could be cleaned up manually in a deterministic way as a part of CI/CD pipelines

**Comment by riisi** [comment]
Similarly, if we could get the name as output, we could use a destroy-time provisioner to delete it with Terraform.

**Comment by vkakde** [comment]
@agocs is this doable? This workaround works nicely for us too.

**Comment by riisi** [comment]
Put this together quickly with Terraform, but if we had the bucket name, we could just use aws cli directly.

```tf
resource "aws_cloudformation_stack" "datadog_forwarder" {
  name         = "${var.name_prefix}-datadog-forwarder"
  capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM", "CAPABILITY_AUTO_EXPAND"]

  parameters = {
    DdApiKeySecretArn = ""
    FunctionName      = "${var.name_prefix}-datadog-forwarder-${random_id.stack.hex}"
    DdTags            = join(",", [for key, value in var.common_tags : "${key}:${value}"])
    DdFetchLambdaTags = true
  }
  template_url = "https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/3.34.0.yaml"

  provisioner "local-exec" {
    when    = destroy
    command = "python ${path.module}/clean_up_forwarder_bucket.py --bucket_name_prefix ${substr(self.name, 0, 30)}"
  }
}
```

```py
import boto3
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("--bucket_name_prefix", type=str, help="Bucket name prefix")
args = parser.parse_args()

s3 = boto3.resource("s3")

if not args.bucket_name_prefix:
    raise Exception("No bucket name prefix supplied")

bucket_name_prefix = args.bucket_name_prefix

print("Bucket name prefix is {}".format(bucket_name_prefix))

forwarder_bucket = None
bucket_count = 0

for bucket in s3.buckets.all():
    if bucket.name.startswith(bucket_name_prefix):
        bucket_count += 1
        forwarder_bucket = bucket

if bucket_count > 1:
    raise Exception("Too many buckets!")

if forwarder_bucket:
    print("Deleting contents of forwarder_bucket: {}".format(forwarder_bucket.name))
    forwarder_bucket.objects.all().delete()

```

**Comment by agocs** [comment]
Hey folks, I'll spend a few hours looking into getting the name of the S3 bucket as a cloudformation output today.

**Comment by tianchu** [comment]
Closing. https://github.com/DataDog/datadog-serverless-functions/pull/484 will be soon released in the next version.
