### ISSUE TITLE
Handler errors are not returned with "level:error"

### ISSUE THREAD

**Issue by arashout** [DataDog/datadog-serverless-functions#498]
**Describe what happened:**
The Datadog Log Forwarder function doesn't seem to add an `level:error` to log messages that are actually errors that have bubbled up to the final lambda handler.

So it's displayed as an INFO log in Datadog instead of ERROR log

**Describe what you expected:**
Expected the error to be have a `level:error` field on the log message so Datadog correct intrepets the log.

**Steps to reproduce the issue:**
Have a simple handler like this with an error:
```go
func handler(ctx context.Context, sqsEvent events.SQSEvent) error {

	err := processSQSEvent(ctx, &sqsEvent)
	if err != nil {
		return errors.Wrap(err, "error processing the SQS event")
	}
	return nil
}

func main() {
	lambda.Start(ddlambda.WrapHandler(handler, nil))
}
```

If `processSQSEvent` returns an `err` you will see "error processing the SQS event" without a log level field being forwarded to datadog.    
   
How can I resolve this?    

Do I need to format the error as a JSON log when returning it?

**Comment by tianchu** [comment]
@arashout do you mind moving the issue to https://github.com/DataDog/datadog-lambda-go instead? I believe it's a golang specific issue. The log forwarder never add the status. The status is determined in the "lambda" log pipeline based on the log content within the Datadog platform. You can find the pipeline in your log configuration page https://app.datadoghq.com/logs/pipelines. I think the issue is that neither AWS nor Golang adds a "status" in the log content itself that we can use with high-level of confidence.

You probably have two options:
1. Log in json (see https://docs.aws.amazon.com/lambda/latest/dg/golang-logging.html#golang-logging-output) with a `status` or `level` field (see https://docs.datadoghq.com/logs/log_configuration/pipelines/?tab=status#status-attribute).
2. Clone the original lambda pipeline, add a custom parsing rule for the logs you consider being errors.

**Comment by arashout** [comment]
Hey @tianchu thanks for the response. I'll post in the Go specific repo.

Yeah we actually already do logging with a structure logger to datadog, but I wanted to address the fact that the error value itself was being logged incorrectly.   

Appreciate the help, I'll close this ticket.
