### ISSUE TITLE
PrivateLink URLs are different from the DNS addresses exposed by the VPC Endpoints

### ISSUE THREAD

**Issue by shshe** [DataDog/datadog-serverless-functions#505]
**Describe what happened:**

Enabling `DD_USE_PRIVATE_LINK=true` on the AWS lambda function is supposed to set the DD URLs to use their PrivateLink addresses. I've added all of the VPC endpoints described here:
https://docs.datadoghq.com/agent/guide/private-link/?tab=metrics

The code block here sets `DD_API_URL` to `https://pvtlink.api.datadoghq.com`:
https://github.com/DataDog/datadog-serverless-functions/blob/master/aws/logs_monitoring/settings.py#L134-L149

However, I have no private DNS mapping for `pvtlink.api.datadoghq.com` after adding all the VPC endpoints.

**Describe what you expected:**

Setting `DD_USE_PRIVATE_LINK=true` should set URLs for private DNS addresses that exist.

**Steps to reproduce the issue:**

Enable `DD_USE_PRIVATE_LINK=true`. Start seeing some 2min timeouts (and getting some pretty expensive lambda charges).

**Workaround:**
I've had to set:
```
DD_USE_PRIVATE_LINK=false
DD_URL: api-pvtlink.logs.datadoghq.com
DD_API_URL: https://api.datadoghq.com
```

**Comment by tianchu** [comment]
@shshe Thanks for reporting this issue! I can confirm this is indeed a problem (ironically) due to our recent effort to simplify PrivateLink configurations for agent users https://github.com/DataDog/documentation/pull/10669. New PrivateLink endpoints were configured so that our regular data intake endpoints would automatically resolve to the PrivateLink endpoints without extra configurations on the agent to override the URLs. However, the endpoint to intake logs from the Forwarder was apparently missed.

I don't think `DD_API_URL: https://api.datadoghq.com` is necessary though, because with `DD_USE_PRIVATE_LINK=false`, `DD_API_URL` would be set to `https://api.datadoghq.com` already https://github.com/DataDog/datadog-serverless-functions/blob/6ad3c5c030b0055641a71bb89dd7385820f31db8/aws/logs_monitoring/settings.py#L107-L110

We are working on setting up a new PrivateLink endpoint for Forwarder log intake as well, and with that endpoint configured, `DD_USE_PRIVATE_LINK` would be fully deprecated for new installations of forwarder, because PrivateLink would work OOB without the need of redirecting to a different set of URLs.
