### ISSUE TITLE
AWS Lambda Forwarder stream log group from another account

### ISSUE THREAD

**Issue by dung-leviethoang-mox** [DataDog/datadog-serverless-functions#541]
**Describe what happened:**
AWS Lambda Forwarder returns below error when try to stream log group from another AWS account.

`Failed to get log group tags due to An error occurred (ResourceNotFoundException) when calling the ListTagsLogGroup operation: The specified log group does not exist`

**Describe what you expected:**

Should have an option to detect log group from the same account or not.

**Steps to reproduce the issue:**

- Create logs destination for aws lambda from account B.
- From account A, add logs Subscription filter to the destination of account B.
- Account A's lambda return above error when try to forward the log group from account B.

**Comment by dung-leviethoang-mox** [comment]
May take a look at https://github.com/DataDog/datadog-serverless-functions/pull/517 to support for multi-account tags fetch.

**Comment by RaphaelAllier** [comment]
Hello,

I'm not sure I understand your issue here, as per AWS [docs](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutSubscriptionFilter.html) you cannot create a subscription filter from one account log group to another account's lambda.
Going to close this issue as part of a cleanup process on our end, feel free to reopen if needed or contact us through our support channels
