### ISSUE TITLE
Latest lambda log forwarder changes function name to lowercase

### ISSUE THREAD

**Issue by jasondbakerspok** [DataDog/datadog-serverless-functions#66]
We just implemented the latest version of the lambda log forwarded and discovered that it is now changing the function name to lowercase in the metadata forwarded to Datadog. This was a breaking change for us because the previous version of the lambda function wasn't doing this and now the new logs are indexed differently from the old logs. 

Is there a reason the function name needs to be lowercase? What is the benefit? We have lots of functions with camelcase names like "test-messaging-transformDataFromSomewhere". Now when a developer goes into Datadog they can no longer cut-and-paste the function name from AWS when doing searches because the name is different.

**Comment by NilsBunge** [comment]
Hello @jasondbakerspok,

First of all sorry for the delay, there have been some changes around those repos and we missed this issue.

So there is indeed a reason for this. As you know, Datadog also offer to [collect metrics from Lambdas](https://docs.datadoghq.com/integrations/amazon_lambda/#metric-collection) and those metrics were tagged with a lowercase function name.

So in order to have a proper link between the function name needed to be lowercase. 
Sorry for the trouble it caused.

We are currently working on adding a versioning on this function in order to better highlight the changes and improvements. 
Hopefully this will help.
